firstCommit
htmlacademy-javascript/2030925-keksobooking-25 pull request #3
Opened 2022-03-23 20:00 UTC by GeorgijSosedov

2022-03-24 19:09 UTC, PolinaShneider commented on js/main.js
> +
У тебя в реквесте фейлятся проверки из-за console.log. Нужно его убрать
<img width="672" alt="image" src="https://user-images.githubusercontent.com/15448200/159992346-abaae62c-4dc5-4621-8c10-969b6b7d420c.png">

2022-03-24 19:10 UTC, PolinaShneider commented on js/main.js
> +    return 'Error';
Давай лучше не возвращать строку 'Error', а выбрасывать ошибку: https://learn.javascript.ru/try-catch#operator-throw

2022-03-24 19:12 UTC, PolinaShneider commented on js/main.js
> +function getRandomFloat (min,max) {
У тебя количество знаков после запятой не учтено
<img width="991" alt="image" src="https://user-images.githubusercontent.com/15448200/159992818-172f05d2-8bb2-447c-a27d-0ebb720d7030.png">

Например, результат может быть 1.1 или 1.1234 в зависимости от третьего параметра

2022-03-24 20:08 UTC, PolinaShneider requested changes
Ты поправил только часть. У тебя из-за console.log валится проверка, а одна функция не соответствует заданию. Давай с этим еще разберемся, ок?

2022-03-24 20:09 UTC, GeorgijSosedov commented
Хорошо:( Тогда на днях ещё запишусь)  пятница, 25 марта 2022г., 01:08 +05:00 от Polina Shneider  ***@***.*** :

***@***.*** requested changes on this pull request.
>Ты поправил только часть. У тебя из-за console.log валится проверка, а одна функция не соответствует заданию. Давай с этим еще разберемся, ок?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-03-24 20:13 UTC, GeorgijSosedov commented
Я просто через консоль в гугле тестировал и результат вроде был такой, какой я и хотел掠 пятница, 25 марта 2022г., 01:08 +05:00 от Polina Shneider  ***@***.*** :

***@***.*** requested changes on this pull request.
>Ты поправил только часть. У тебя из-за console.log валится проверка, а одна функция не соответствует заданию. Давай с этим еще разберемся, ок?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-03-24 20:15 UTC, PolinaShneider commented
Это я поняла, но перед окрытием реквеста вывод в консоль нужно убрать — гитхаб ругается
<img width="940" alt="image" src="https://user-images.githubusercontent.com/15448200/160002342-990b9a0a-8cdd-44d7-8959-cc645b251d13.png">

2022-03-24 20:16 UTC, GeorgijSosedov commented
Ой, это моя невнимательность))))) я первую почту не увидел вообще, сейчас попробую разобраться пятница, 25 марта 2022г., 01:15 +05:00 от Polina Shneider  ***@***.*** :

>Это я поняла, но перед окрытием реквеста вывод в консоль нужно убрать — гитхаб ругается
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-03-25 22:52 UTC, PolinaShneider commented on js/main.js
> +    return random.toFixed(3);
Близко, но не совсем. 

Во-первых, количество знаков после запятой нужно передавать аргументом (согласно заданию, это третий параметр). А не хардкодить тройку, как это делаешь ты.

Во-вторых, результат .toFixed() — строка, а не число. Тебе нужно сделать это числом

<img width="218" alt="image" src="https://user-images.githubusercontent.com/15448200/160212036-8db4ef14-3881-40c8-9463-c877130b90bc.png">

2022-03-28 20:32 UTC, PolinaShneider commented on js/main.js
> +    throw new SyntaxError ('Ваше число меньше минимального!');
Это не SyntaxError по сути. Просто аргументы невалидные. Можно было написать просто `throw 'Ваше число меньше минимального!'`

2022-03-28 20:32 UTC, merged

2022-10-11 08:18 UTC, GeorgijSosedov commented
Хорошо, изменю тогда
Спасибо!!  вторник, 29 марта 2022г., 01:32 +05:00 от Polina Shneider  ***@***.*** :

***@***.*** commented on this pull request.
>----------------------------------------------------------------------
>In  js/main.js :
> +
>+function getRandom (min, max) {
>+  if (min >= 0 && max >= min) {
>+    return Math.floor(Math.random() * (max - min)) + min;
>+  } else {
>+    throw new SyntaxError ('Ваше число меньше минимального!');
>+  }
>+}
>+getRandom (1,11);
>+
>+function getRandomFloat (min,max,commas = 3) {
>+  const random = min + Math.random() * (max + 1 - min);
>+  if (min >=0 && max >= min) {
>+    return random.toFixed(commas) * 1;
>+  } else {
>+    throw new SyntaxError ('Ваше число меньше минимального!');
>
>Это не SyntaxError по сути. Просто аргументы невалидные. Можно было написать просто throw 'Ваше число меньше минимального!'
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>